-- Run this in Supabase SQL Editor

create table if not exists leads (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),

  -- Business info
  business_name text not null,
  address text,
  phone text,
  website text,
  email text,
  industry text,
  city text,

  -- Outreach state
  sequence_step integer default 0,          -- 0=not sent, 1=first email sent, 2=follow-up sent
  status text default 'queued',             -- queued | sent | replied | bounced | unsubscribed | converted
  scheduled_send_at timestamptz,            -- when to send the next email
  last_sent_at timestamptz,

  -- Email content (generated by Gemini)
  email_subject text,
  email_body text,
  followup_subject text,
  followup_body text,

  -- Notes
  notes text
);

-- Index for the sender cron query
create index if not exists leads_send_queue
  on leads (scheduled_send_at, status, sequence_step)
  where status = 'queued';
